app:
    resource: '@AppBundle/Controller/'
    type: annotation

login:
    path: /login
    defaults: { _controller: AppBundle:Security:login }

user_registration:
    path: /signup
    defaults: { _controller: AppBundle:Security:signup }