<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLirskqx\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLirskqx/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerLirskqx.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerLirskqx\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerLirskqx\appDevDebugProjectContainer([
    'container.build_hash' => 'Lirskqx',
    'container.build_id' => '409e8e8d',
    'container.build_time' => 1580124206,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLirskqx');
