<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYmnsaur\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYmnsaur/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerYmnsaur.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerYmnsaur\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerYmnsaur\appDevDebugProjectContainer([
    'container.build_hash' => 'Ymnsaur',
    'container.build_id' => 'cd7deae1',
    'container.build_time' => 1580299216,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYmnsaur');
