<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9hoxz52\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9hoxz52/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container9hoxz52.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container9hoxz52\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container9hoxz52\appDevDebugProjectContainer([
    'container.build_hash' => '9hoxz52',
    'container.build_id' => 'ed8b8324',
    'container.build_time' => 1580894158,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9hoxz52');
