<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWykprja\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWykprja/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWykprja.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWykprja\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerWykprja\appDevDebugProjectContainer([
    'container.build_hash' => 'Wykprja',
    'container.build_id' => '1fcb8522',
    'container.build_time' => 1578264545,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWykprja');
